const AuthorsActionTypes = {
  FETCH_AUTHOR_START: 'FETCH_AUTHOR_START',
  FETCH_AUTHOR_SUCCESS: 'FETCH_AUTHOR_SUCCESS',
  FETCH_AUTHOR_FAILURE: 'FETCH_AUTHOR_FAILURE'
};

export default AuthorsActionTypes;