const BooksActionTypes = {
  SEARCH_START: 'SEARCH_START',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  SEARCH_FAILURE: 'SEARCH_SUCCESS',
  CLEAR_SEARCH_RESULTS: 'CLEAR_SEARCH_RESULTS',
  CLEAR_SEARCH_QUERY: 'CLEAR_SEARCH_QUERY',
  FETCH_BOOK_START: 'FETCH_BOOK_START',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
  CLEAR_BOOK: 'CLEAR_BOOK'
};

export default BooksActionTypes;
