const BooksActionTypes = {
  FETCH_BOOK_START: 'FETCH_BOOK_START',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
  CLEAR_BOOK: 'CLEAR_BOOK'
};

export default BooksActionTypes;
