const BooksActionTypes = {
  FETCH_BOOK_START: 'FETCH_BOOK_START',
  FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
  FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
  FETCH_BOOK_STATUS_START: 'FETCH_BOOK_STATUS_START',
  FETCH_BOOK_STATUS_SUCCESS: 'FETCH_BOOK_STATUS_SUCCESS',
  FETCH_BOOK_STATUS_FAILURE: 'FETCH_BOOK_STATUS_FAILURE',
  UPDATE_BOOK_STATUS_START: 'UPDATE_BOOK_STATUS_START',
  UPDATE_BOOK_STATUS_SUCCESS: 'UPDATE_BOOK_STATUS_SUCCESS',
  UPDATE_BOOK_STATUS_FAILURE: 'UPDATE_BOOK_STATUS_FAILURE',
  FETCH_BOOK_RATING_START: 'FETCH_BOOK_RATING_START',
  FETCH_BOOK_RATING_SUCCESS: 'FETCH_BOOK_RATING_SUCCESS',
  FETCH_BOOK_RATING_FAILURE: 'FETCH_BOOK_RATING_FAILURE',
  UPDATE_BOOK_RATING_START: 'UPDATE_BOOK_RATING_START',
  UPDATE_BOOK_RATING_SUCCESS: 'UPDATE_BOOK_RATING_SUCCESS',
  UPDATE_BOOK_RATING_FAILURE: 'UPDATE_BOOK_RATING_FAILURE',
  FETCH_USER_BOOKS_START: 'FETCH_USER_BOOKS_START',
  FETCH_USER_BOOKS_SUCCESS: 'FETCH_USER_BOOKS_SUCCESS',
  FETCH_USER_BOOKS_FAILURE: 'FETCH_USER_BOOKS_FAILURE',
};

export default BooksActionTypes;
