const UserActionTypes = {
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCES',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  ADD_BOOK_TO_SHELF_START: 'ADD_BOOK_TO_SHELF_START',
  ADD_BOOK_TO_SHELF_SUCCESS: 'ADD_BOOK_TO_SHELF_SUCCESS',
  ADD_BOOK_TO_SHELF_FAILURE: 'ADD_BOOK_TO_SHELF_FAILURE'
};

export default UserActionTypes;
